export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_FAIL="SIGNIN_FAIL";

export const FETCH_ALL_DOCTORS_SUCCESS="FETCH_ALL_DOCTORS_SUCCESS";
export const FETCH_ALL_DOCTORS_FAIL="FETCH_ALL_DOCTORS_FAIL";
export const FETCH_ALL_DOCTORS_LOADING="FETCH_ALL_DOCTORS_LOADING";
export const CREATE_DOCTOR_LOADING="CREATE_DOCTOR_LOADING";
export const CREATE_DOCTOR_SUCCESS="CREATE_DOCTOR_SUCCESS";
export const CREATE_DOCTOR_FAIL="CREATE_DOCTOR_FAIL"

export const FETCH_ALL_DEPARTMENTS_SUCCESS="FETCH_ALL_DEPARTMENTS_SUCCESS";
export const FETCH_ALL_DEPARTMENTS_FAIL="FETCH_ALL_DEPARTMENTS_FAIL";
export const FETCH_ALL_DEPARTMENTS_LOADING="FETCH_ALL_DEPARTMENT_LOADING";
export const CREATE_DEPARTMENT_LOADING="CREATE_DEPARTMENT_LOADING";
export const CREATE_DEPARTMENT_SUCCESS="CREATE_DEPARTMENT_SUCCESS";
export const CREATE_DEPARTMENT_FAIL="CREATE_DEPARTMENT_FAIL"
export const DELETE_DEPARTMENT_LOADING="DELETE_DEPARTMENT_LOADING";
export const DELETE_DEPARTMENT_SUCCESS="DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAIL="DELETE_DEPARTMENT_FAIL"
export const FETCH_ONE_DEPARTMENT_LOADING="FETCH_ONE_DEPARTMENT_LOADING";
export const FETCH_ONE_DEPARTMENT_SUCCESS="FETCH_ONE_DEPARTMENT_SUCCESS";
export const FETCH_ONE_DEPARTMENT_FAIL="FETCH_ONE_DEPARTMENT_FAIL"
export const UPDATE_DEPARTMENT_LOADING="UPDATE_DEPARTMENT_LOADING";
export const UPDATE_DEPARTMENT_SUCCESS="UPDATE_DEPARTMENT_SUCCES";
export const UPDATE_DEPARTMENT_FAIL="UPDATE_DEPARTMENT_FAIL"

export const FETCH_ALL_APPOINTMENT_SUCCESS="FETCH_ALL_APPOINTMENT_SUCCESS";
export const FETCH_ALL_APPOINTMENT_FAIL="FETCH_ALL_APPOINTMENT_FAIL";
export const FETCH_ALL_APPOINTMENT_LOADING="FETCH_ALL_APPOINTMENT_LOADING";
export const CREATE_APPOINTMENT_LOADING="CREATE_APPOINTMENT_LOADING";
export const CREATE_APPOINTMENT_SUCCESS="CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL="CREATE_APPOINTMENT_FAIL"
